name: younov-prod-lbweb

services:
  lb:
    image: docker.io/library/nginx:1.27-alpine
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped

  web:
    build:
      context: ../../..
      dockerfile: infra/web/Dockerfile
    # Web 容器内部监听 3000（见 infra/web/nginx.conf）
    expose:
      - "3000"
    restart: unless-stopped

